version: '3.9'

services:
  db:
    image: postgres:15.2-alpine3.17
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: fastapi_db
    volumes:
      - data:/var/lib/postgresql/data

  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: fastapi_service
    command: >
      sh -c "
        uvicorn main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

volumes:
  data:
